galaxy_info:
  author: foodcoops.net admins
  description: Role to setup a basic virtual server
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - Trixie
