# This certainly needs some attention. We might want to fork these repo's too.

roles:
  - name: foodcoops.foodsoft
    src: https://github.com/foodcoops/ansible-role-foodsoft.git
    scm: git

  - name: senselab.borgbackup
    src: https://git.systemausfall.org/senselab/ansible-role-borgbackup.git
    scm: git

  - name: senselab.configure-firewall
    src: https://git.systemausfall.org/senselab/ansible-role-configure-firewall.git
    scm: git

  - name: senselab.dehydrated
    src: https://git.systemausfall.org/senselab/ansible-role-dehydrated.git
    scm: git

  - name: senselab.mariadb
    src: https://git.systemausfall.org/senselab/ansible-role-mariadb.git
    scm: git

  - name: senselab.nginx
    src: https://git.systemausfall.org/senselab/ansible-role-nginx.git
    scm: git

  - name: senselab.postfix
    src: https://git.systemausfall.org/senselab/ansible-role-postfix.git
    scm: git

  - name: foodcoops.sharedlists
    src: https://github.com/foodcoops/ansible-role-sharedlists.git
    scm: git


collections:
  - name: adhawkins.borgbase
